export const SCREEN_NAME = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  PATIENT_LOGIN: 'PatientLogin',
  DOCTOR_LOGIN: 'DoctorLogin',
  REGISTER: 'Register',
  VERIFY_EMAIL: 'VerifyEmail',
  PATIENT_HOME: 'PatientHome',
  DOCTOR_HOME: 'DoctorHome',
  HOME: 'Home',
  FUNCTION: 'Function',
  AI: 'AI',
  REPORT: 'Report',
  PERSONAL: 'Personal',
  PATIENT_SERVICES: 'PatientServices',
  PATIENT_DOCTORS: 'PatientDoctors',
  PATIENT_CONSULTATION: 'PatientConsultation',
  PATIENT_PAYMENT: 'PatientPayment',
  PATIENT_NOTIFICATIONS: 'PatientNotifications',
  PATIENT_PROMOTIONS: 'PatientPromotions',
} as const;
