export const SCREEN_NAME = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  PATIENT_LOGIN: 'PatientLogin',
  DOCTOR_LOGIN: 'DoctorLogin',
  REGISTER: 'Register',
  VERIFY_EMAIL: 'VerifyEmail',
  PATIENT_HOME: 'PatientHome',
  DOCTOR_HOME: 'DoctorHome',
  HOME: 'Home',
  FUNCTION: 'Function',
  AI: 'AI',
  REPORT: 'Report',
  PERSONAL: 'Personal',
};
