export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  ADMIN: {
    ROOT: "/admin",
    USERS: "/admin/users",
    SCHEDULES: "/admin/schedules",
    DOCTORS: "/admin/doctors",
    SERVICES: "/admin/services",
    PROMOTIONS: "/admin/promotions",
    FINANCE: "/admin/finance",
    REPORTS: "/admin/reports",
    REVIEWS: "/admin/reviews",
    MARKETING: "/admin/marketing",
    SETTINGS: "/admin/settings",
  },
  RECEPTIONIST: {
    ROOT: "/receptionist",
    APPOINTMENTS: "/receptionist/appointments",
    APPOINTMENTS_NEW: "/receptionist/appointments/new",
    PATIENTS: "/receptionist/patients",
    PATIENTS_NEW: "/receptionist/patients/new",
    CHECK_IN: "/receptionist/check-in",
    BILLING: "/receptionist/billing",
  },
  DOCTOR: {
    ROOT: "/doctor",
    SCHEDULE: "/doctor/schedule",
    PATIENTS: "/doctor/patients",
    MEDICAL_RECORDS: "/doctor/medical-records",
    PRESCRIPTIONS: "/doctor/prescriptions",
    TREATMENT_PLANS: "/doctor/treatment-plans",
    CONSULTATIONS: "/doctor/consultations",
  },
} as const;
